lang: es 
website:
  google-analytics: "G-4D5QFYD1KS"
  cookie-consent: true

project:
  type: book  
  output-dir: docs  

  
book:
  title: "Python: De explorador de datos a analista"
  # language: es
  # author: Guillermo Barrios
  # version: 0.9.1
  navbar:
    search: True
  sidebar:
    menu: True
    collapse-level: 1
    border: true
    logo: img/python.png
  page-footer:
    left:  Logo  por  Dnu72, [CC BY-SA 4.0](<https://creativecommons.org/licenses/by-sa/4.0>), via Wikimedia Commons.
    center: "[Repositorio](https://github.com/altamarmx/analista)"
    right: Construido con [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  repo-url: https://github.com/altamarmx/analista/
  chapters:
    - index.qmd
    - part: "Recomendaciones y datos"
      chapters:
        - uso.qmd
        - datos.qmd
    - part: notebooks/semanaUno/semana1.qmd
      chapters: 
        - notebooks/semanaUno/001_instala_python.qmd
        - notebooks/semanaUno/002_intro_powershell.qmd
        - notebooks/semanaUno/003_venvs.qmd
        - notebooks/semanaUno/004_espacio_trabajo_venv.qmd
        - notebooks/semanaUno/005_desarrolla_paquetes.qmd
        - notebooks/semanaUno/006_PEP8.ipynb
        - notebooks/semanaUno/007_PiensaPOO.ipynb
        - notebooks/semanaUno/008_try_except_finally.ipynb
        - notebooks/semanaUno/009_decoradores.ipynb
        - notebooks/semanaUno/010_unpack.ipynb
        - notebooks/semanaUno/011_lambda.ipynb
        - notebooks/semanaUno/012_walrus.ipynb
    - part: notebooks/semanaDos/semana2.qmd 
      chapters: 
        - notebooks/semanaDos/013_IntroMatplotlib.ipynb
        - notebooks/semanaDos/014_POOMatplotlib.ipynb
        - notebooks/semanaDos/015_DecoradoresMatplotlib.ipynb
        - notebooks/semanaDos/016_TemasMatplotlib.ipynb
        - notebooks/semanaDos/017_InteractivasMatplotlib.ipynb
        - notebooks/semanaDos/018_EstructuraDatos_OWD.ipynb
        - notebooks/semanaDos/019_Intro_Plotly.ipynb
        - notebooks/semanaDos/020_Intro_Bokeh.ipynb
        - notebooks/semanaDos/021_Intro_Altair.ipynb
        - notebooks/semanaDos/022a_Matplotlib.ipynb
        - notebooks/semanaDos/022b_Plotly.ipynb
        # - notebooks/semanaDos/022c_Bokeh.ipynb
        # - notebooks/semanaDos/022d_Altair.ipynb
    - part: notebooks/semanaTres/semana3.qmd
      chapters: 
        - notebooks/semanaTres/024_Intro_pandas.ipynb
        - notebooks/semanaTres/025_Promedios_moviles.ipynb
        - notebooks/semanaTres/026_Desplazamientos.ipynb
        - notebooks/semanaTres/027_parquet.ipynb
        - notebooks/semanaTres/028_groupby.ipynb
        - notebooks/semanaTres/029_pivot_table.ipynb
        - notebooks/semanaTres/030_update_dataframe.ipynb
        - notebooks/semanaTres/031_decoradores_pandas.ipynb
        - notebooks/semanaTres/032_join_merge_concat.ipynb
        - notebooks/semanaTres/033_datos_faltantes.ipynb
        - notebooks/semanaTres/034_zonas_horarias.ipynb
    # - part: notebooks/semanaCuatro/semana4.qmd
    #   chapters: 
    #     # - notebooks/semanaCuatro/concepto_espacio_trabajo.qmd
    #     - notebooks/semanaCuatro/concatena.ipynb
    #     - notebooks/semanaCuatro/multiindex_columnas.ipynb
    #     - notebooks/semanaCuatro/multiindex_indice.ipynb
    #     - notebooks/semanaCuatro/Encoding.ipynb
    #     - notebooks/semanaCuatro/paquetes_locales.ipynb
    #     # - notebooks/semanaCuatro/mensajes.ipynb
    #     - notebooks/semanaCuatro/EF_EDA.ipynb
    #     - notebooks/semanaCuatro/EF_LimpiezaDatos.ipynb
    #     - notebooks/semanaCuatro/EF_Analisis.ipynb
    #     - notebooks/semanaCuatro/Paquetes.ipynb
    # - creditos.qmd
format:
  html: 
    theme: 
      light: cerulean
      dark: darkly
    code-link: true

